# Stable rustfmt option
reorder_modules = false
use_field_init_shorthand = true
use_small_heuristics = "Max"
newline_style = "Unix"
normalize_comments = true

# Nightly rustfmt options
max_width = 100
comment_width = 100
imports_granularity = "Crate"
wrap_comments = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 100
format_macro_matchers = true
format_strings = true
group_imports = "One"
match_block_trailing_comma = true
overflow_delimited_expr = true
reorder_impl_items = true