[package]
name = "fuzztools"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
alloy.workspace = true
alloy-rlp.workspace = true
rand.workspace = true
rayon.workspace = true
thiserror.workspace = true
tokio.workspace = true
secp256k1.workspace = true
anyhow.workspace = true
mutable.workspace = true
serde = "1.0.228"
serde_json = "1.0.145"
reqwest = "0.12.25"

[lib]
path = "crates/lib.rs"
